name: "CD"

on: "push"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Run Rubocop
        uses: OpenSourcePolitics/lint-action@master
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Run RSpec
        run: bundle exec rspec
  deploy:
    runs-on: ubuntu-latest
    if: "github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main'"
    needs: [lint, tests]
    steps:
      - name: Deploy container
        uses: OpenSourcePolitics/deploy-container-action@master
        with:
          registry: ${{ vars.REGISTRY_URL }}
          namespace: ${{ vars.REGISTRY_NAMESPACE }}
          password: ${{ secrets.TOKEN }}
          access_key: ${{ secrets.ACCESS_TOKEN }}
          image_name: ${{ vars.REGISTRY_IMAGE_NAME }}
          tag: latest
          container_name: ${{ vars.CONTAINER_NAME }}
          project_id: ${{ secrets.SCALEWAY_PROJECT_ID }}